### ISSUE TITLE
ModuleNotFoundError: No module named 'ccnet'：树莓派安装seafile-server_7.1.4_pi-buster-stable后无法启动seahub

### ISSUE THREAD

**Issue by x1n9snv0** [haiwen/seafile-rpi#64] opened 2020-09-08 03:02 UTC
树莓派版本`Linux raspberry 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux`
截止发布issue时是最新的。
按照seafile文档中[Deploying Seafile with MySQL](https://download.seafile.com/published/seafile-manual/deploy/using_mysql.md)的说明，解决所有依赖后执行`./setup-seafile-mysql.sh `，过程如下：
```
Checking python on this machine ...

-----------------------------------------------------------------
This script will guide you to setup your seafile server using MySQL.
Make sure you have read seafile server manual at

        https://download.seafile.com/published/seafile-manual/home.md

Press ENTER to continue
-----------------------------------------------------------------


What is the name of the server? It will be displayed on the client.
3 - 15 letters or digits
[ server name ] raspsea

What is the ip or domain of the server?
For example: www.mycompany.com, 192.168.1.101
[ This server's ip or domain ] 192.168.8.119

Which port do you want to use for the seafile fileserver?
[ default "8082" ]     

-------------------------------------------------------
Please choose a way to initialize seafile databases:
-------------------------------------------------------

[1] Create new ccnet/seafile/seahub databases
[2] Use existing ccnet/seafile/seahub databases

[ 1 or 2 ] 1

What is the host of mysql server?
[ default "localhost" ] 

What is the port of mysql server?
[ default "3306" ] 

What is the password of the mysql root user?
[ root password ] 

verifying password of user root ...  done

Enter the name for mysql user of seafile. It would be created if not exists.
[ default "seafile" ] 

Enter the password for mysql user "seafile":
[ password for seafile ] 

verifying password of user seafile ...  done

Enter the database name for ccnet-server:
[ default "ccnet-db" ] 

Enter the database name for seafile-server:
[ default "seafile-db" ] 

Enter the database name for seahub:
[ default "seahub-db" ] 

---------------------------------
This is your configuration
---------------------------------

    server name:            raspsea
    server ip/domain:       192.168.8.119

    seafile data dir:       /opt/seafile/seafile-data
    fileserver port:        8082

    database:               create new
    ccnet database:         ccnet-db
    seafile database:       seafile-db
    seahub database:        seahub-db
    database user:          seafile



---------------------------------
Press ENTER to continue, or Ctrl-C to abort
---------------------------------

Generating ccnet configuration ...

done
Successly create configuration dir /opt/seafile/ccnet.
Generating seafile configuration ...

Done.
done
Generating seahub configuration ...

----------------------------------------
Now creating ccnet database tables ...

----------------------------------------
----------------------------------------
Now creating seafile database tables ...

----------------------------------------
----------------------------------------
Now creating seahub database tables ...

----------------------------------------

creating seafile-server-latest symbolic link ...  done




-----------------------------------------------------------------
Your seafile server configuration has been finished successfully.
-----------------------------------------------------------------

run seafile server:     ./seafile.sh { start | stop | restart }
run seahub  server:     ./seahub.sh  { start <port> | stop | restart <port> }

-----------------------------------------------------------------
If you are behind a firewall, remember to allow input/output of these tcp ports:
-----------------------------------------------------------------

port of seafile fileserver:   8082
port of seahub:               8000

When problems occur, Refer to

        https://download.seafile.com/published/seafile-manual/home.md

for information.
```
安装完毕后的目录结构：
```
root@raspberry:/opt/seafile # tree ./ -L 2
./
|-- ccnet
|-- conf
|   |-- ccnet.conf
|   |-- gunicorn.conf.py
|   |-- seafdav.conf
|   |-- seafile.conf
|   `-- seahub_settings.py
|-- installed
|   `-- seafile-server_7.1.4_pi-buster-stable.tar.gz
|-- seafile-data
|   `-- library-template
|-- seafile-server-7.1.4
|   |-- check_init_admin.py
|   |-- reset-admin.sh
|   |-- runtime
|   |-- seaf-fsck.sh
|   |-- seaf-fuse.sh
|   |-- seaf-gc.sh
|   |-- seafile
|   |-- seafile.sh
|   |-- seahub
|   |-- seahub.sh
|   |-- setup-seafile-mysql.py
|   |-- setup-seafile-mysql.sh
|   |-- setup-seafile.sh
|   |-- sql
|   `-- upgrade
|-- seafile-server-latest -> seafile-server-7.1.4
`-- seahub-data
    `-- avatars

14 directories, 16 files
```
启动`seafile`：
```
root@raspberry:/opt/seafile/seafile-server-7.1.4 # ./seafile.sh start

[09/08/20 09:26:27] ../common/session.c(148): using config file /opt/seafile/conf/ccnet.conf
[warn] Unable to parse nameserver address fe80::266f:8cff:fefb:e0df%wlan0
Starting seafile server, please wait ...
** Message: 09:26:27.236: seafile-controller.c(541): No seafevents.

Seafile server started

Done.
```
启动`seahub`：
```
root@raspberry:/opt/seafile/seafile-server-7.1.4 # ./seahub.sh start 

Starting seahub at port 8000 ...
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-7.1.4/check_init_admin.py", line 351, in <module>
    rpc = RPC()
  File "/opt/seafile/seafile-server-7.1.4/check_init_admin.py", line 284, in __init__
    import ccnet
ModuleNotFoundError: No module named 'ccnet'
```
请教如何解决，感谢各位大佬！

**Comment by jobenvil** [comment] 2020-09-08 18:31
The problem is already commented on the official Seafile support forum:
https://forum.seafile.com/

**Comment by cm9vdA** [comment] 2020-09-22 07:33
修改seahub.sh， 将export PYTHONPATH那一行的python3.6改为python3.7

**Comment by Gustl22** [comment] 2020-10-12 12:03
Very strange: there was only a `seafile-server-7.1.4/seafile/lib/python2.7` folder, although I used the `build3.sh` script to build the server file. Have both python versions installed (python2.7 and python3.8). System: arm64 / arm-v8 (Ubuntu-Server) on Raspberry-PI. So could't start seahub by rewriting `seahub.sh`, cause of lots of unresolved / deprecated dependencies.
How can I force to use python3 ? May would be good to have a durable fix for this bug :grinning:

**Comment by jobenvil** [comment] 2020-10-12 12:13
@Gustl22 this is most probably because you have default python = 2.7 (system wide) or you didn't set correctly the PYTHONPATH while compiling. I use linux containers (OS: Buster, Bionic, Stretch) to build seafile.

**Comment by Gustl22** [comment] 2020-10-12 15:37
@jobenvil Thank you, I uninstalled python2 with `sudo apt purge python2.7-minimal`. Now it's using the right python version.

**Comment by jobenvil** [comment] 2022-01-07 14:12
The Seafile forum is your friend for the nex time. Closing.

**Closed as completed by jobenvil** 2022-01-07 14:12 UTC
