### ISSUE TITLE
cannot setting data directory

### ISSUE THREAD

**Issue by kweonsunho** [haiwen/seafile-rpi#66] opened 2020-09-22 04:14 UTC
root@raspberrypi:/var/www/seafile/seafile-server-7.1.4# sudo ./setup-seafile-mysql.sh
Checking python on this machine ...

-----------------------------------------------------------------
This script will guide you to setup your seafile server using MySQL.
Make sure you have read seafile server manual at

https://download.seafile.com/published/seafile-manual/home.md

Press ENTER to continue
-----------------------------------------------------------------

What is the name of the server? It will be displayed on the client.
3 - 15 letters or digits
[ server name ] Air

What is the ip or domain of the server?
For example: www.mycompany.com, 192.168.1.101
[ This server's ip or domain ] airnas.duckdns.org

Which port do you want to use for the seafile fileserver?
[ default "8082" ]

-------------------------------------------------------
Please choose a way to initialize seafile databases:
-------------------------------------------------------

[1] Create new ccnet/seafile/seahub databases
[2] Use existing ccnet/seafile/seahub databases

[ 1 or 2 ] 1

What is the host of mysql server?
[ default "localhost" ]

What is the port of mysql server?
[ default "3306" ]

What is the password of the mysql root user?
[ root password ]
What is the password of the mysql root user?
[ root password ]

verifying password of user root ...
verifying password of user root ... done

Enter the name for mysql user of seafile. It would be created if not exists.
[ default "seafile" ]

Enter the password for mysql user "seafile":
[ password for seafile ]

verifying password of user seafile ... done

Enter the database name for ccnet-server:
[ default "ccnet-db" ]

Enter the database name for seafile-server:
[ default "seafile-db" ]

Enter the database name for seahub:
[ default "seahub-db" ]

---------------------------------
This is your configuration
---------------------------------

server name: Air
server ip/domain: airnas.duckdns.org

seafile data dir: /var/www/seafile/seafile-data
fileserver port: 8082

database: create new
ccnet database: ccnet-db
seafile database: seafile-db
seahub database: seahub-db
database user: seafile

---------------------------------
Press ENTER to continue, or Ctrl-C to abort
---------------------------------
this is log, so I can't setting seaffile data directory, What can i do?

**Comment by cm9vdA** [comment] 2020-09-22 07:45
I created a soft link to seafile-data for the data directory, and it works.

**Comment by kweonsunho** [comment] 2020-09-22 23:45
> I created a soft link to seafile-data for the data directory, and it works.

oh, it is good idea.

**Comment by kweonsunho** [comment] 2020-09-22 23:49
> > I created a soft link to seafile-data for the data directory, and it works.
> 
> oh, it is good idea.

What is link command?

> I created a soft link to seafile-data for the data directory, and it works.

What is link command?

**Comment by cm9vdA** [comment] 2020-09-23 03:48
> > > I created a soft link to seafile-data for the data directory, and it works.
> > 
> > 
> > oh, it is good idea.
> 
> What is link command?
> 
> > I created a soft link to seafile-data for the data directory, and it works.
> 
> What is link command?

You can try the following steps:
1. Stop Seafile and Seahub Server.
2. Rename `/var/www/seafile/seafile-data` to `/var/www/seafile/seafile-data.bak`.
3. Run `ln -s XXX /var/www/seafile/seafile-data`, XXX is the directory where you want to save the data.
4. Copy all files in `/var/www/seafile/seafile-data.bak` to `/var/www/seafile/seafile-data`.
5. Start Seafile and Seahub Server.

**Comment by jobenvil** [comment] 2022-01-07 14:14
I think the issue is not actual. Closing.

**Closed as completed by jobenvil** 2022-01-07 14:14 UTC

**Comment by RandallAnjie** [comment] 2022-03-03 11:57
I created a soft link, but the server down with the webside shows: 502 Bad Gateway nginx/1.18.0 (Ubuntu)
BTW, my server is Ubuntu 20.04 on raspberryPi 4B

**Comment by Gustl22** [comment] 2022-04-06 21:59
@Zhuanjier if I remember correctly, even without a valid Data directory you should see the server running. 
Anything interesting in /seafile/logs/seahub.log or seafile.log, whats the output, if starting the server or service?
